# Generated by Django 2.2 on 2019-05-12 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagegap', '0003_auto_20190512_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Spending',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagegap.Category')),
            ],
        ),
        migrations.CreateModel(
            name='MinWage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wage', models.IntegerField()),
                ('last_update', models.DateField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagegap.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('last_update', models.DateField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagegap.Country')),
                ('spending', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagegap.Spending')),
            ],
        ),
    ]
